actions

diff --git a/installation b/installation
--- a/installation
+++ b/installation
@@ -7,3 +7,10 @@ if [ $USERID -ne 0 ]; then
 fi 
 echo "installing nginx" 
 dnf install nginx -y
+
+ if [$? -ne 0 ]; then
+    echo "nginx installation failed"
+    exit 1
+    else
+    echo "nginx installed successfully"
+ fi
