actions

diff --git a/installation b/installation
--- a/installation
+++ b/installation
@@ -6,11 +6,27 @@ if [ $USERID -ne 0 ]; then
    exit 1
 fi 
 echo "installing nginx" 
-dnf remove nginx -y
+dnf install nginx -y
 
  if [ "$?" -ne 0 ]; then
-    echo "nginx remove failed"
+    echo "nginx install failed"
     exit 1
     else
-    echo "nginx removed successfully"
+    echo "nginx installed successfully"
  fi
+ dnf install mysql -y
+
+   if [ "$?" -ne 0 ]; then
+      echo "mysql install failed"
+      exit 1
+      else
+      echo "mysql installed successfully"
+   fi
+   dnf install nodejs -y
+
+     if [ "$?" -ne 0 ]; then
+        echo "nodejs install failed"
+        exit 1
+        else
+        echo "nodejs installed successfully"
+     fi
